version: '3'

services: 
 postgres:
  image: postgres:12.7-alpine
  ports: 
   - 5433:5432
  environment:
   POSTGRES_PASSWORD: postgres
   POSTGRES_USER: postgres
  restart: always
  volumes: 
   - ./data/pgdata:/var/lib/postgresql/data
 mysql: 
  image: mysql:8.0.26
  container_name: mysql
  ports: 
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: anw
  restart: always
  volumes:
   - ./data/mysqldata:/var/lib/mysql
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
  container_name: es01
  ports:
   - 9200:9200
   - 9300:9300
  environment:
   - discovery.type=single-node
  restart: always
  volumes:
   - ./data/elasticsearch:/usr/share/elasticsearch/data
  networks: 
   - elastic
 kibana:
  image: docker.elastic.co/kibana/kibana:7.14.0
  container_name: kib01
  ports: 
   - 5601:5601
  environment:
   ELASTICSEARCH_URL: http://es01:9200
   ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
  restart: always
  networks: 
   - elastic
 grafana:
  image: grafana/grafana-enterprise
  container_name: grafana-container
  ports:
   - 4001:3000
  restart: always
  volumes:
   - ./data/grafana:/var/lib/grafana
  user: "472" 
 mautic:
  image: mautic/mautic:latest
  container_name: mautic
  depends_on:
    - mysql
  ports:
    - 9000:80
  volumes:
    - ./data/mautic:/var/www/html
  environment:
    - MAUTIC_DB_HOST=172.18.0.3
    - MYSQL_PORT_3306_TCP=3306
    - MAUTIC_DB_USER=root
    - MAUTIC_DB_PASSWORD=root
    - MAUTIC_DB_NAME=mautic
    - MAUTIC_RUN_CRON_JOBS=true
networks: 
 elastic:
  external: true
    

  
